<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>runner01</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>61a151a8-52a5-48f2-aceb-4be4a71eb30b</testSuiteGuid>
   <testCaseLink>
      <guid>1af57e44-2294-4e89-994a-6a40469af337</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>031b4d4d-0607-489e-8f7f-0e889a0ee6e6</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/login_data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>031b4d4d-0607-489e-8f7f-0e889a0ee6e6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>66f67e4b-85a8-4eda-acaf-e5f25894ce0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>031b4d4d-0607-489e-8f7f-0e889a0ee6e6</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>6254ac7e-1b1f-4555-baf0-0a3c8125024b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
